services:
  # сервис БД
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # проброс порта
    ports:
      - "5432:5432"
    # том для хранения
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

    # проверка что бд готова
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


  # приложение
  app:
    # собираемся в текущей директории
    build: .
    # проброс
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      PR_SERVICE_BASE_URL: ${PR_SERVICE_BASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}

    # запускаемся после успешного старта БД
    depends_on:
      db:
        condition: service_healthy

# создаем том для postgres
volumes:
  pgdata: